apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "releaseName" . }}-cert
spec:
  dnsNames:
        {{- range $host := .Values.ingress.hosts }}
     - {{ $host.name}}
    {{- end }}
  secretName: {{ template "releaseName" . }}
  issuerRef:
    name: {{ template "releaseName" . }}-cert
    kind: Issuer
